name: "DonAQ's Blag"
favicon: null
layout_spectrum: 0.79147
typography_spectrum: 0.32637
title: The Blag of Don AQ
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#010101'
    - '#fffffd'
    - '#8e1303'
    - '#eb830a'
    - '#f1d58f'
  brandStrength: 0.125
  lightness: 0.125
  saturation: 0.3125
  rhythmicContrast: 0.75
purpose: []
