name: "DonAQ's Blag"
favicon: null
layout_spectrum: 0.9631249085068703
typography_spectrum: 0.6997268642298877
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.6545308385975659
  lightness: 0.6351718460209668
  saturation: 0.37683524284511805
  rhythmicContrast: 0.5518574491143227
purpose: []
