name: "DonAQ's Blag"
favicon: null
layout_spectrum: 0.92164
typography_spectrum: 0.6997268642298877
title: The Blag of Don AQ
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#010101'
    - '#fffffd'
    - '#8e1303'
    - '#eb830a'
    - '#f1d58f'
  brandStrength: 0.5625
  lightness: 0.375
  saturation: 0.5625
  rhythmicContrast: 0.5518574491143227
purpose: []
